### PR TITLE
Completely rework of reading/receiving messages

### PR DESCRIPTION
**Pull request by pfichtner**
Reading of (serial line) data was optimized for messages split by separators, but not all protocols work like this: There are protocols that split messages in other ways. Perhaps there are/could be protocols which read chunks of fixed length or even messages without a monotonic but some way of dynamic separator. 

So the protocol handling was placed upside down: Instead of telling the Reader how to split the incoming messages there are protocol handlers which push back there messages into the system if the detected the end of a message (e.g. by seeing a separator but perhaps by something completely different). 

This is a preparation to support more/other protocols then Ardulink(2) proto. The support for another protocol (Firmata) is included but not activated since this is work in progress.

### CODE REVIEW

**Comment by PizzaProgram** [comment]
Great Work!

May I ask:
 - Does this break the compatibility with previous serial connections?
 - Do the same .INO files still work?
 - Will this new connection have better handling of accidentally disconnection / reconnection of the serial port?
 - How about force-naming the boards, to identify better which board is which, even if com ports are getting mixed?

**Comment by pfichtner** [comment]
> Great Work!

Thank you :smile:

>     * Does this break the compatibility with previous serial connections?

Of course it doesen't. For that reason there's a "protocol concept": So if we would make incompatible changes we would add an new protocol (version) while the old keeps available/usable

>     * Do the same .INO files still work?

Yes, because the protocol is untouched, just the way serial data was processed internally was changed. It was a refactoring what means that the observable behavior was not changed. 
Now there's even [a test verifying the sketch works as expected in my new project](https://github.com/pfichtner/virtualavr/blob/main/demo/java/sketchtest/src/test/java/com/ardulink/sketch/ArdulinkFirmwareTest.java), perhaps I'll move this tests into Ardulink-2 (where it should reside in)

>     * Will this new connection have better handling of accidentally disconnection / reconnection of the serial port?

Nothing was changed on how connections are handled. 

>     * How about force-naming the boards, to identify better which board is which, even if com ports are getting mixed?

Don't know the problem. On Linux you could use `/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0` instead of `/dev/ttyUSB0` to address a certain com port. If you are on Windows I don't know how COM ports are handled there. 

If there is an issue where Ardulink does not work than expected or you have a proposal for an improvement please feel free to open an issue or discussion.

**Comment by PizzaProgram** [comment]
Thank you very much for the detailed answers!
PS:
Under windows >> there is no possibility to reach a device by it's serial number.
That's why it would be much safer, if both the INO file had a line something like this:
`name="" // fill this to force-check and enable connection. If empty = not safe = not checked.`

**Comment by pfichtner** [comment]
> Thank you very much for the detailed answers! PS: Under windows >> there is no possibility to reach a device by it's serial number. That's why it would be much safer, if both the INO file had a line something like this: `name="" // fill this to force-check and enable connection. If empty = not safe = not checked.`

That way you would have to compile the ino for each board separately (which hasn't to be an issue but the compiled sketch should be general in my opinion). 
If having a name Ardulink would have to iterate over the serial connections, connect to board by board until it connected to a board having the expected name set. Sounds interesting but would impact some work on both sides.

**Comment by PizzaProgram** [comment]
> That way you would have to compile the ino for each board separately

Yes, but you have to upload the compiled files to the boards one by one anyway. Changing `"basement_pump1"` to `"addict_lamps3"` is not a big deal, but a highly recommended safety. (And easier to distinguish each one.)

> ...but the compiled sketch should be general in my opinion).

I do not see any logical reason for this. Just the opposite.  
_As I've already wrote 2 years ago: if by any chance 2 boards are getting switched by a software, it may result that instead of turning on a lamp, my metallic roller shutter would go down, cutting off a child's head under it. This and similar event may happen at my simple smart-home house. You can imagine the scale of failures during industrial usage._

> If having a name Ardulink would have to iterate over the serial connections

Yes, that is a secondary, **optional** goal, making it more "plug&play" / user friendly.
But at **first** stage it is enough if the name is checked after connection, and:
- if name mismatch or
- there is an other board already connected with same name,  
 
the connection would be **dropped** with a proper error msg. That is ca. 3 lines of code. Nothing special.

**Firmata** can be renamed by changing the name of the .INO file. But the name-checking is not implemented there neither :-( ... I've been asking them 2 years ago. If I had more time, I would enhance there myself. Learned JS during last year only to be able to enhance Node-RED plugins.

**Comment by PizzaProgram** [comment]
... we may move this conversation to a new ticket ?

**Pull request merged**
